# Anthropic Claude Configuration Example
# Copy this file to config/demo_config.yaml and add your API key

demo:
  mode: "ai"
  duration: 90
  trials: 3
  grid_model: "2bus-13bus"

ai:
  # Anthropic Claude settings
  model: "claude-3-opus-20240229"
  api_base: "https://api.anthropic.com/v1"
  api_key: "sk-ant-your-anthropic-api-key-here"  # Replace with your actual API key
  
  # Model parameters optimized for Claude
  temperature: 0.8
  max_tokens: 4000
  top_p: 0.95
  frequency_penalty: 0.0
  presence_penalty: 0.0
  
  # Request settings (Claude can be slower)
  timeout: 90
  retry_attempts: 3
  retry_delay: 3

attack:
  prompt: "Conduct a comprehensive security assessment of the power grid infrastructure, identifying critical vulnerabilities and developing strategic attack vectors"
  max_concurrent_attacks: 4
  attack_timeout: 45
  validation_mode: "strict"
  voltage_limit_min: 0.7
  voltage_limit_max: 1.3
  max_power_injection: 5000000

# Rest of configuration uses defaults from main config