# Local Qwen3 Model Configuration (Default)
# This represents the default configuration for the nginx-lb setup

demo:
  mode: "comparison"
  duration: 60
  trials: 3
  grid_model: "2bus-13bus"

ai:
  # Local Qwen3 model via nginx-lb
  model: "Qwen/Qwen3-30B-A3B"
  api_base: "http://nginx-lb/v1"
  api_key: ""  # No API key needed for local setup
  
  # Model parameters optimized for Qwen3
  temperature: 0.8
  max_tokens: 4000
  top_p: 0.95
  frequency_penalty: 0.0
  presence_penalty: 0.0
  
  # Request settings
  timeout: 60
  retry_attempts: 3
  retry_delay: 2

attack:
  prompt: "Demonstrate AI-driven strategic attack progression targeting grid vulnerabilities"
  max_concurrent_attacks: 5
  attack_timeout: 30
  validation_mode: "strict"
  voltage_limit_min: 0.7
  voltage_limit_max: 1.3
  max_power_injection: 5000000

grid:
  helics:
    broker_address: "tcp://helics-broker:23406"
    federate_name: "mcp_attacker"
    time_delta: 1.0
    period: 1.0
    log_level: "warning"
  
  monitoring:
    update_interval: 0.1
    history_size: 1000
    anomaly_detection: true

docker:
  compose_file: "docker-compose.demo.yml"
  build_on_start: false
  cleanup_on_exit: true
  startup_timeout: 120

logging:
  level: "INFO"
  file: "demo_results/demo.log"
  console: true

results:
  directory: "demo_results"
  save_raw_data: true
  generate_plots: false
  format: "json"